from .gmm import gmm
from .max_diff import max_diff
from .stdev import stdev
from .phrase import phrase_frequency
from .frequency import frequent_words_diff
from .apostrophes import apostrophe_discrepancies
from .quotes import quote_discrepancies
from .chars import ascii_discrepancies
from .split_points import split_points
from .chars import text_length
from .chars import  num_paragraphs
from .spellings import spelling_discrepancies
from .split_points import calculate_weights
from .split_points_count import split_points_count
from .split_points_count import calculate_weights_count
